Handle mixed case schema names DAT-10027
liquibase/liquibase-snowflake pull request #176
Opened 2022-05-27 15:58 UTC by wwillard7800

2022-05-30 14:22 UTC, KushnirykOleh commented
@wwillard7800 we are moving snowflake from extension to liquibase-core, https://github.com/liquibase/liquibase/pull/2841, so most likely changes in SnowflakeDatabase.java will make sense to replicate there after my PR is merged

2022-05-31 19:44 UTC, nvoxland requested changes

2022-05-31 19:44 UTC, nvoxland commented on src/main/java/liquibase/ext/snowflake/database/SnowflakeDatabase.java
> +    public String getLiquibaseSchemaName() {
I don't think we need any of these methods to be overriden do we? The default logic should be good as long as SnowflakeDatabase is correctly saying schema names are stored as uppercase?

2022-06-21 21:25 UTC, nvoxland commented
These changes were applied in the liquibase-core version

2022-06-21 21:25 UTC, closed without merging